Repository wanted-wecode-subjects/freshcode-subject, pull requests merged in 2021-11, with the labels that each got.

#21 feat: create menu
  src/menus/dto/create-menu.dto.ts
  src/menus/menus.controller.ts
  src/menus/menus.repository.ts
  src/menus/menus.service.ts
Labels: feat

#23 feat: 카테고리 생성 - #22
  src/categories/categories.controller.ts
  src/categories/categories.repository.ts
  src/categories/categories.service.ts
  src/categories/dto/create-category.dto.ts
Labels: feat

#26 feat : 카테고리 조회(findOne, find)
  src/categories/categories.controller.ts
  src/categories/categories.module.ts
  src/categories/categories.service.ts
Labels: feat

#28 feat : 카테고리 수정
  src/categories/categories.controller.ts
  src/categories/categories.repository.ts
  src/categories/categories.service.ts
  src/categories/dto/create-update-category.dto.ts
Labels: feat

#30 feat: 카테고리 삭제 - #29
  src/categories/categories.controller.ts
  src/categories/categories.service.ts
Labels: feat

#32 feat: 카테고리 이름 검색
  src/categories/categories.service.ts
Labels: feat

#39 feat: menu 생성 기능 추가
  src/categories/entities/category.entity.ts
  src/menus/dto/create-menu.dto.ts
  src/menus/entities/menu.entity.ts
  src/menus/menus.controller.ts
  src/menus/menus.module.ts
  src/menus/menus.repository.ts
  src/menus/menus.service.ts
Labels: feat

#40 feat: menus 조회
  src/categories/entities/category.entity.ts
  src/menus/entities/menu.entity.ts
  src/menus/menus.controller.ts
  src/menus/menus.service.ts
Labels: feat

#43 feat: 메뉴 삭제
  src/menus/menus.controller.ts
  src/menus/menus.service.ts
Labels: feat

#42 feat: 메뉴 업데이트
  src/categories/entities/category.entity.ts
  src/menus/dto/update-menu.dto.ts
  src/menus/entities/menu.entity.ts
  src/menus/menus.controller.ts
  src/menus/menus.service.ts
Labels: feat

#54 feat: menus ownership 적용
  src/auth/auth.module.ts
  src/menus/menus.controller.ts
  src/menus/menus.module.ts
  src/menus/menus.service.ts
Labels: feat

#61 feat: 메뉴 리스트 페이징 추가
  src/menus/menus.controller.ts
  src/menus/menus.service.ts
Labels: feat

#66 feat: 메뉴 - 태그 연결
  src/menus/dto/relation-menu-tag.dto.ts
  src/menus/menus.controller.ts
  src/menus/menus.module.ts
  src/menus/menus.service.ts
  src/tags/tags.module.ts
Labels: feat

#70 test: menus 유닛 테스트
  src/app.controller.spec.ts
  src/auth/auth.service.ts
  src/menus/menus.service.spec.ts
Labels: test

#75 feat: jwtAuthGuard apply
  src/items/items.controller.ts
  src/menus/menus.controller.ts
  src/menus/menus.service.spec.ts
  src/tags/tags.controller.ts
Labels: bug, feat
